export const products = [
  {
    id: "fc20-1",
    label: "DRYING CABINET",
    name: "ProLine FC20",
    weight: "44lb",
    kg: "20kg",
    image: "/product0.png",
    price: 1399,
  },
  {
    id: "fc20-2",
    label: "DRYING CABINET XL",
    name: "ProLine FC20 XL",
    weight: "55lb",
    kg: "25kg",
    image: "/product1.png",
    price: 1599,
  },
  {
    id: "fc20-3",
    label: "DRYING CABINET ECO",
    name: "ProLine FC20 Eco",
    weight: "40lb",
    kg: "18kg",
    image: "/product2.png",
    price: 1299,
  },
  {
    id: "fc20-4",
    label: "DRYING CABINET PRO",
    name: "ProLine FC20 Pro",
    weight: "60lb",
    kg: "27kg",
    image: "/product3.png",
    price: 1799,
  },
  {
    id: "ws10-1",
    label: "WASHING MACHINE",
    name: "EcoWash 3000",
    weight: "48lb",
    kg: "22kg",
    image: "/product4.png",
    price: 999,
  },
  {
    id: "ws10-2",
    label: "WASHING MACHINE XL",
    name: "EcoWash 4000",
    weight: "52lb",
    kg: "24kg",
    image: "/product5.png",
    price: 1199,
  },
  {
    id: "ds10-1",
    label: "DRYER",
    name: "DryMax Turbo",
    weight: "46lb",
    kg: "21kg",
    image: "/product6.png",
    price: 1099,
  },
  {
    id: "ds10-2",
    label: "DRYER COMPACT",
    name: "DryMax Compact",
    weight: "38lb",
    kg: "17kg",
    image: "/product7.png",
    price: 899,
  },
  {
    id: "ir10-1",
    label: "IRONING SYSTEM",
    name: "SteamPro Iron",
    weight: "20lb",
    kg: "9kg",
    image: "/product8.png",
    price: 799,
  },
  {
    id: "ir10-2",
    label: "IRONING TABLE",
    name: "IronBoard Plus",
    weight: "25lb",
    kg: "11kg",
    image: "/product9.png",
    price: 699,
  },
  {
    id: "hs10-1",
    label: "HEATING SYSTEM",
    name: "HeatMaster 500",
    weight: "58lb",
    kg: "26kg",
    image: "/product10.png",
    price: 1499,
  },
  {
    id: "hs10-2",
    label: "HEATING SYSTEM ECO",
    name: "HeatEco 200",
    weight: "50lb",
    kg: "23kg",
    image: "/product11.png",
    price: 1199,
  },
];
