import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({
  colors: {
    brand: [
      "#fff7a7",
      "#fff698",
      "#fff589",
      "#fff37b",
      "#fff26c",
      "#e6da61",
      "#ccc256",
      "#b3a94c",
      "#999141",
      "#807936",
    ],
  },
  primaryColor: "brand",
  primaryShade: 4,
  fontFamily: '"Darker Grotesque", sans-serif',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
