import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import cx from "clsx";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import Header from "@/components/Header";

import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  Container,
  mantineHtmlProps,
} from "@mantine/core";
import Footer from "@/components/Footer";
import CartProvider from "@/context/cart_context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({
  colors: {
    brand: [
      "#fff7a7",
      "#fff698",
      "#fff589",
      "#fff37b",
      "#fff26c",
      "#e6da61",
      "#ccc256",
      "#b3a94c",
      "#999141",
      "#807936",
    ],
  },
  primaryColor: "brand",
  primaryShade: 4,
  fontFamily: '"Darker Grotesque", sans-serif',
  headings: {
    fontFamily: '"Archivo Black",sans-serif',
    sizes: {
      h3: {
        fontWeight: "500",

        fontSize: "32px",
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
